name: instagram
version: 1.0.0-beta+2
description: Dart Instagram client library.
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/thosakwe/instagram_dart
environment:
  sdk: ">=1.19.0"
dependencies:
  oauth2: ^1.0.0
  owl: ^0.2.1
dev_dependencies:
  build_runner: ^0.3.0
  owl_codegen: ^0.2.1
  test: ^0.12.0
